# Generated by Django 3.2.9 on 2021-11-23 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cbvapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Color_Name', models.CharField(default='Default', max_length=200, unique=True)),
                ('cat_status', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Note_Title', models.CharField(max_length=200)),
                ('Description', models.TextField()),
                ('Note_Count', models.IntegerField(default=0)),
                ('Reminder_Date', models.DateTimeField()),
                ('Pinned_Note', models.BooleanField(default=False)),
                ('Favourite_Note', models.BooleanField(default=False)),
                ('post_status', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('Note_Color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cbvapp.colors')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Priority_Name', models.CharField(default='Default', max_length=200, unique=True)),
                ('cat_status', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.RemoveField(
            model_name='blog',
            name='blog_category',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='posted_by',
        ),
        migrations.RemoveField(
            model_name='category',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='blog',
        ),
        migrations.DeleteModel(
            name='contactus',
        ),
        migrations.RemoveField(
            model_name='hashtag',
            name='blog',
        ),
        migrations.DeleteModel(
            name='newsletter',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='comment',
        ),
        migrations.DeleteModel(
            name='hashtag',
        ),
        migrations.AddField(
            model_name='note',
            name='Note_Priority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cbvapp.priority'),
        ),
        migrations.AddField(
            model_name='note',
            name='posted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
